"""End-to-end tests for the ingestion → review → release → retrieval path.

Fixtures are synthetic placeholders: no real legal content is embedded here, and no
credential is hard-coded (each test token is generated by the test itself).
"""

from __future__ import annotations

import json
import sys
import tempfile
import unittest
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from fastapi.testclient import TestClient

from law_rag.api.app import create_app
from law_rag.api.bootstrap import (
    BootstrapConfig,
    BootstrapUser,
    build_container,
    config_from_env,
    load_config_file,
    parse_config,
)
from law_rag.ingestion.knowledge_models import ValidityStatus
from law_rag.retrieval.validity import derive_validity_status

API = "/api/v1"

SYNTHETIC_DOCUMENT = """Luật số: 99/2026/SYNTH
Cơ quan ban hành: Cơ quan tổng hợp
Ngày ban hành: 15 tháng 11 năm 2026
Có hiệu lực từ: 01 tháng 12 năm 2026
LUẬT TỔNG HỢP VỀ NỘI DUNG KIỂM THỬ

Chương I
Điều 1. Phạm vi điều chỉnh
1. Văn bản tổng hợp này quy định nội dung kiểm thử hệ thống.

Điều 2. Thời hạn giải quyết
1. Thời hạn giải quyết thủ tục tổng hợp là 15 ngày làm việc.
"""

TOKENS = {
    "u_bootstrap_admin": "test-admin-token-00000001",
    "u_bootstrap_reviewer": "test-reviewer-token-00002",
    "u_bootstrap_reader": "test-reader-token-000003",
}

CONFIG_PAYLOAD = {
    "users": [
        {
            "user_id": "u_bootstrap_admin",
            "username": "admin",
            "email": "admin@example.invalid",
            "display_name": "Quản trị tri thức",
            "roles": ["knowledge_admin"],
            "token_env": "TOKEN_ADMIN",
        },
        {
            "user_id": "u_bootstrap_reviewer",
            "username": "reviewer",
            "email": "reviewer@example.invalid",
            "display_name": "Người duyệt",
            "roles": ["reviewer"],
            "token_env": "TOKEN_REVIEWER",
        },
        {
            "user_id": "u_bootstrap_reader",
            "username": "reader",
            "email": "reader@example.invalid",
            "display_name": "Người đọc",
            "roles": ["user"],
            "token_env": "TOKEN_READER",
        },
    ],
    "collections": [
        {
            "collection_id": "col_ingest",
            "name": "Bộ sưu tập kiểm thử",
            "description": "Synthetic collection",
            "is_public": False,
        }
    ],
    "grants": [
        {"user_id": "u_bootstrap_admin", "collection_id": "col_ingest", "access_level": "admin"}
    ],
}

ENVIRON = {
    "TOKEN_ADMIN": TOKENS["u_bootstrap_admin"],
    "TOKEN_REVIEWER": TOKENS["u_bootstrap_reviewer"],
    "TOKEN_READER": TOKENS["u_bootstrap_reader"],
}


def _auth(user_id: str) -> dict[str, str]:
    return {"Authorization": f"Bearer {TOKENS[user_id]}"}


class BootstrapConfigTests(unittest.TestCase):
    def test_rejects_unknown_roles(self) -> None:
        payload = json.loads(json.dumps(CONFIG_PAYLOAD))
        payload["users"][0]["roles"] = ["not_a_role"]
        with self.assertRaises(ValueError):
            parse_config(payload)

    def test_rejects_grants_for_unknown_entities(self) -> None:
        payload = json.loads(json.dumps(CONFIG_PAYLOAD))
        payload["grants"][0]["collection_id"] = "col_missing"
        with self.assertRaises(ValueError):
            parse_config(payload)

        payload = json.loads(json.dumps(CONFIG_PAYLOAD))
        payload["grants"][0]["user_id"] = "u_missing"
        with self.assertRaises(ValueError):
            parse_config(payload)

    def test_rejects_duplicate_identifiers(self) -> None:
        payload = json.loads(json.dumps(CONFIG_PAYLOAD))
        payload["collections"].append(dict(payload["collections"][0]))
        with self.assertRaises(ValueError):
            parse_config(payload)

    def test_config_from_env_reads_file_and_overrides(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            config_path = Path(tmp) / "bootstrap.json"
            config_path.write_text(json.dumps(CONFIG_PAYLOAD), encoding="utf-8")
            config = config_from_env(
                {
                    "LAW_RAG_CONFIG_FILE": str(config_path),
                    "LAW_RAG_BLOB_DIR": str(Path(tmp) / "blobs"),
                    "LAW_RAG_OCR_ENABLED": "1",
                }
            )
            assert config is not None
            self.assertEqual(config.blob_dir, str(Path(tmp) / "blobs"))
            self.assertTrue(config.ocr_enabled)
            self.assertEqual(len(config.users), 3)

    def test_config_from_env_without_file(self) -> None:
        self.assertIsNone(config_from_env({}))


class ChunkingRobustnessTests(unittest.TestCase):
    def test_chunking_skips_nodes_without_their_own_text(self) -> None:
        """An article whose text sits in its clauses must not become an empty chunk."""
        from law_rag.ingestion.extraction import extract_document
        from law_rag.ingestion.legal_parsing import parse_legal_document
        from law_rag.retrieval.chunking import chunk_legal_document

        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "synthetic-law.txt"
            path.write_text(SYNTHETIC_DOCUMENT, encoding="utf-8")
            extraction = extract_document(path, original_filename="synthetic-law.txt")
            result = parse_legal_document(extraction, job_id="job-chunk")
            _, chunks = chunk_legal_document(result, "ver-chunk", "u_bootstrap_admin")

        self.assertTrue(chunks)
        self.assertTrue(all(chunk.content.strip() for chunk in chunks))
        # Only the clause bodies carry text in this fixture.
        self.assertEqual({chunk.node_kind for chunk in chunks}, {"clause"})


class ValidityDerivationTests(unittest.TestCase):
    def test_future_effective_date_is_not_yet_effective(self) -> None:
        self.assertIs(
            derive_validity_status(
                effective_date=date(2030, 1, 1), expiry_date=None, today=date(2026, 9, 29)
            ),
            ValidityStatus.NOT_YET_EFFECTIVE,
        )

    def test_past_expiry_date_is_expired(self) -> None:
        self.assertIs(
            derive_validity_status(
                effective_date=date(2020, 1, 1), expiry_date=date(2021, 1, 1), today=date(2026, 9, 29)
            ),
            ValidityStatus.EXPIRED,
        )

    def test_current_dates_are_in_force(self) -> None:
        self.assertIs(
            derive_validity_status(
                effective_date=date(2026, 3, 1), expiry_date=None, today=date(2026, 9, 29)
            ),
            ValidityStatus.IN_FORCE,
        )


class IngestionPipelineApiTests(unittest.TestCase):
    """Full vertical slice driven through the public API."""

    @classmethod
    def setUpClass(cls) -> None:
        cls._tmp = tempfile.TemporaryDirectory()
        config = BootstrapConfig(
            users=tuple(
                BootstrapUser(
                    user_id=entry["user_id"],
                    username=entry["username"],
                    email=entry["email"],
                    display_name=entry["display_name"],
                    roles=tuple(entry["roles"]),
                    token_env=entry["token_env"],
                )
                for entry in CONFIG_PAYLOAD["users"]
            ),
            collections=parse_config(CONFIG_PAYLOAD).collections,
            grants=parse_config(CONFIG_PAYLOAD).grants,
            blob_dir=str(Path(cls._tmp.name) / "blobs"),
        )
        result = build_container(config, environ=ENVIRON)
        cls.container = result.container
        cls.client = TestClient(create_app(result.container))
        cls.job_id = ""

    @classmethod
    def tearDownClass(cls) -> None:
        cls._tmp.cleanup()

    # --- helpers ----------------------------------------------------------
    def _upload(self, user_id: str, content: str = SYNTHETIC_DOCUMENT, key: str = "key-1"):
        return self.client.post(
            f"{API}/documents/upload",
            params={"filename": "synthetic-law.txt"},
            headers={**_auth(user_id), "Idempotency-Key": key, "Content-Type": "text/plain"},
            content=content.encode("utf-8"),
        )

    def _pending_tasks(self, user_id: str, job_id: str) -> list[dict]:
        response = self.client.get(f"{API}/jobs/{job_id}/review", headers=_auth(user_id))
        self.assertEqual(response.status_code, 200, response.text)
        return response.json()["tasks"]

    # --- tests ------------------------------------------------------------
    def test_01_upload_requires_idempotency_key(self) -> None:
        response = self.client.post(
            f"{API}/documents/upload",
            params={"filename": "synthetic-law.txt"},
            headers={**_auth("u_bootstrap_admin"), "Content-Type": "text/plain"},
            content=SYNTHETIC_DOCUMENT.encode("utf-8"),
        )
        self.assertEqual(response.status_code, 422)
        self.assertEqual(response.json()["error"]["code"], "VALIDATION_FAILED")

    def test_02_upload_runs_extraction_and_parsing(self) -> None:
        response = self._upload("u_bootstrap_admin")
        self.assertEqual(response.status_code, 202, response.text)
        receipt = response.json()
        type(self).job_id = receipt["job_id"]

        job = self.client.get(f"{API}/jobs/{self.job_id}", headers=_auth("u_bootstrap_admin")).json()
        self.assertEqual(job["status"], "review_required")
        self.assertIn("xếp hàng trích xuất", " ".join(receipt["warnings"]))

        state = self.client.get(
            f"{API}/jobs/{self.job_id}/review", headers=_auth("u_bootstrap_admin")
        ).json()
        self.assertGreater(len(state["metadata"]), 0)
        self.assertGreater(len(state["preview"]), 0)
        self.assertTrue(state["review_required"])
        self.assertIsNone(state["approved_version_id"])

    def test_03_job_status_needs_an_ingestion_permission(self) -> None:
        """A role without document.upload/audit.view cannot read job status (403)."""
        response = self.client.get(f"{API}/jobs/{self.job_id}", headers=_auth("u_bootstrap_reviewer"))
        self.assertEqual(response.status_code, 403)

    def test_03b_reviewer_can_read_the_review_state_of_someone_elses_job(self) -> None:
        """Review is a separate role: the reviewer must see jobs uploaded by others."""
        response = self.client.get(
            f"{API}/jobs/{self.job_id}/review", headers=_auth("u_bootstrap_reviewer")
        )
        self.assertEqual(response.status_code, 200, response.text)
        self.assertGreater(len(response.json()["tasks"]), 0)

    def test_03c_regular_user_cannot_read_someone_elses_review_state(self) -> None:
        response = self.client.get(
            f"{API}/jobs/{self.job_id}/review", headers=_auth("u_bootstrap_reader")
        )
        self.assertEqual(response.status_code, 403)

    def test_04_reader_cannot_submit_review_decisions(self) -> None:
        response = self.client.post(
            f"{API}/jobs/{self.job_id}/review",
            json={"decisions": [{"item_kind": "metadata", "item_id": "meta-1", "action": "accept"}]},
            headers=_auth("u_bootstrap_reader"),
        )
        self.assertEqual(response.status_code, 403)

    def test_05_approval_is_blocked_until_pending_items_are_decided(self) -> None:
        """Unreviewed items must produce a conflict, never a 5xx."""
        response = self.client.post(
            f"{API}/jobs/{self.job_id}/approve",
            json={"collection_id": "col_ingest", "acknowledged_warnings": []},
            headers=_auth("u_bootstrap_admin"),
        )
        self.assertEqual(response.status_code, 409, response.text)
        self.assertIn("unverified", response.json()["error"]["message"])

    def test_06_review_decisions_clear_pending_items(self) -> None:
        tasks = self._pending_tasks("u_bootstrap_admin", self.job_id)
        self.assertTrue(tasks)

        decisions = [
            {
                "item_kind": task["item_kind"],
                "item_id": task["item_id"],
                # Unverified relation candidates are rejected: the reviewer confirms
                # only what the parser can support (docs/06, ADR-011).
                "action": "reject" if task["item_kind"] == "relation" else "accept",
            }
            for task in tasks
        ]
        response = self.client.post(
            f"{API}/jobs/{self.job_id}/review",
            json={"decisions": decisions},
            headers=_auth("u_bootstrap_admin"),
        )
        self.assertEqual(response.status_code, 200, response.text)
        state = response.json()
        self.assertEqual(state["tasks"], [])

    def test_07_approval_requires_write_access_on_the_collection(self) -> None:
        state = self.client.get(
            f"{API}/jobs/{self.job_id}/review", headers=_auth("u_bootstrap_admin")
        ).json()
        response = self.client.post(
            f"{API}/jobs/{self.job_id}/approve",
            json={
                "collection_id": "col_ingest",
                "acknowledged_warnings": state["warnings"],
            },
            headers=_auth("u_bootstrap_reviewer"),
        )
        self.assertEqual(response.status_code, 403)

    def test_08_approval_releases_and_indexes_the_document(self) -> None:
        state = self.client.get(
            f"{API}/jobs/{self.job_id}/review", headers=_auth("u_bootstrap_admin")
        ).json()
        response = self.client.post(
            f"{API}/jobs/{self.job_id}/approve",
            json={
                "collection_id": "col_ingest",
                "acknowledged_warnings": state["warnings"],
            },
            headers=_auth("u_bootstrap_admin"),
        )
        self.assertEqual(response.status_code, 200, response.text)
        approval = response.json()
        self.assertEqual(approval["status"], "indexed")
        self.assertGreater(approval["chunk_count"], 0)
        self.assertEqual(approval["validity_status"], "not_yet_effective")
        type(self).document_id = approval["document_id"]

        job = self.client.get(f"{API}/jobs/{self.job_id}", headers=_auth("u_bootstrap_admin")).json()
        self.assertEqual(job["status"], "indexed")

    def test_09_released_document_is_searchable_with_citations(self) -> None:
        response = self.client.post(
            f"{API}/search",
            json={"query": "thời hạn giải quyết", "top_k": 5},
            headers=_auth("u_bootstrap_admin"),
        )
        self.assertEqual(response.status_code, 200, response.text)
        results = response.json()["results"]
        self.assertTrue(results)
        self.assertEqual(results[0]["document_number"], "99/2026/SYNTH")
        self.assertTrue(results[0]["is_verified"])

        chat = self.client.post(
            f"{API}/chat",
            json={"question": "Thời hạn giải quyết là bao lâu?", "top_k": 5},
            headers=_auth("u_bootstrap_admin"),
        )
        self.assertEqual(chat.status_code, 200, chat.text)
        body = chat.json()
        self.assertFalse(body["insufficient_evidence"])
        self.assertTrue(body["citations"])
        citation = body["citations"][0]
        self.assertEqual(citation["validity_status"], "not_yet_effective")
        self.assertTrue(citation["viewer_url"])

    def test_10_document_reads_are_acl_filtered(self) -> None:
        document = self.client.get(
            f"{API}/documents/{self.document_id}", headers=_auth("u_bootstrap_admin")
        )
        self.assertEqual(document.status_code, 200)
        self.assertEqual(document.json()["document"]["collection_ids"], ["col_ingest"])

        hidden = self.client.get(
            f"{API}/documents/{self.document_id}", headers=_auth("u_bootstrap_reader")
        )
        self.assertEqual(hidden.status_code, 404)

        listing = self.client.get(f"{API}/documents", headers=_auth("u_bootstrap_reader")).json()
        self.assertEqual(listing["count"], 0)

        search = self.client.post(
            f"{API}/search",
            json={"query": "thời hạn giải quyết", "top_k": 5},
            headers=_auth("u_bootstrap_reader"),
        ).json()
        self.assertEqual(search["results"], [])

    def test_11_collections_endpoint_reports_effective_access(self) -> None:
        admin = self.client.get(f"{API}/collections", headers=_auth("u_bootstrap_admin")).json()
        self.assertEqual(admin["count"], 1)
        self.assertEqual(admin["collections"][0]["access_level"], "admin")

        reader = self.client.get(f"{API}/collections", headers=_auth("u_bootstrap_reader")).json()
        self.assertEqual(reader["count"], 0)

    def test_12_retry_is_only_allowed_for_failed_jobs(self) -> None:
        response = self.client.post(f"{API}/jobs/{self.job_id}/retry", headers=_auth("u_bootstrap_admin"))
        self.assertEqual(response.status_code, 409)

    def test_13_audit_sink_records_the_whole_flow(self) -> None:
        """docs/10 requires an audit trail for upload, review, approval and release."""
        actions = [event["action"] for event in self.container.audit.events]
        self.assertIn("upload", actions)
        self.assertIn("job_transition", actions)
        self.assertIn("review_metadata", actions)
        self.assertIn("approve_document", actions)
        self.assertIn("release_document", actions)

    def test_14_example_bootstrap_config_is_valid(self) -> None:
        """The shipping config/bootstrap.example.json must parse and bootstrap cleanly."""
        example_path = Path(__file__).resolve().parents[1] / "config" / "bootstrap.example.json"
        self.assertTrue(example_path.is_file(), f"Missing config file: {example_path}")
        config = load_config_file(example_path)
        self.assertEqual(len(config.users), 5)
        self.assertEqual(len(config.collections), 3)
        self.assertEqual(len(config.grants), 5)
        result = build_container(config)
        self.assertIsNotNone(result.container)
        self.assertEqual(len(result.tokens), 5)



if __name__ == "__main__":
    unittest.main()
